# Simple workflow for deploying static content to GitHub Pages
name: Deploy Report to Pages

on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  tests:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
      TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
      TRELLO_API_SECRET: ${{ secrets.TRELLO_API_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install chromium
      - name: Run Playwright tests
        run: npx playwright test
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './playwright-report'
      

  publishTestResults:
    name: "Publish Test Results to to testresults.marcusfelling.com"
    needs:
      [
        tests,
      ]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        id: download

      - name: Publish to GH Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          publish_branch: main
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ${{steps.download.outputs.download-path}}
          keep_files: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
